In [1]:
import nltk

In [5]:
movie_reviews = nltk.corpus.movie_reviews.words()

In [8]:
nltk.corpus.movie_reviews.fileids()

['neg/cv000_29416.txt',
 'neg/cv001_19502.txt',
 'neg/cv002_17424.txt',
 'neg/cv003_12683.txt',
 'neg/cv004_12641.txt',
 'neg/cv005_29357.txt',
 'neg/cv006_17022.txt',
 'neg/cv007_4992.txt',
 'neg/cv008_29326.txt',
 'neg/cv009_29417.txt',
 'neg/cv010_29063.txt',
 'neg/cv011_13044.txt',
 'neg/cv012_29411.txt',
 'neg/cv013_10494.txt',
 'neg/cv014_15600.txt',
 'neg/cv015_29356.txt',
 'neg/cv016_4348.txt',
 'neg/cv017_23487.txt',
 'neg/cv018_21672.txt',
 'neg/cv019_16117.txt',
 'neg/cv020_9234.txt',
 'neg/cv021_17313.txt',
 'neg/cv022_14227.txt',
 'neg/cv023_13847.txt',
 'neg/cv024_7033.txt',
 'neg/cv025_29825.txt',
 'neg/cv026_29229.txt',
 'neg/cv027_26270.txt',
 'neg/cv028_26964.txt',
 'neg/cv029_19943.txt',
 'neg/cv030_22893.txt',
 'neg/cv031_19540.txt',
 'neg/cv032_23718.txt',
 'neg/cv033_25680.txt',
 'neg/cv034_29446.txt',
 'neg/cv035_3343.txt',
 'neg/cv036_18385.txt',
 'neg/cv037_19798.txt',
 'neg/cv038_9781.txt',
 'neg/cv039_5963.txt',
 'neg/cv040_8829.txt',
 'neg/cv041_22364.txt',


In [9]:
dir(nltk.corpus.movie_reviews)

['CorpusView',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__unicode__',
 '__weakref__',
 '_add',
 '_c2f',
 '_delimiter',
 '_encoding',
 '_f2c',
 '_file',
 '_fileids',
 '_get_root',
 '_init',
 '_map',
 '_para_block_reader',
 '_pattern',
 '_read_para_block',
 '_read_sent_block',
 '_read_word_block',
 '_resolve',
 '_root',
 '_sent_tokenizer',
 '_tagset',
 '_unload',
 '_word_tokenizer',
 'abspath',
 'abspaths',
 'categories',
 'encoding',
 'ensure_loaded',
 'fileids',
 'open',
 'paras',
 'raw',
 'readme',
 'root',
 'sents',
 'unicode_repr',
 'words']

In [15]:
nltk.corpus.movie_reviews.words('neg/cv006_17022.txt')

['so', 'ask', 'yourself', 'what', '"', '8mm', '"', '(', ...]

In [30]:

for x in nltk.corpus.movie_reviews.fileids():
    if 'pos' in x:
        print(x)

pos/cv000_29590.txt
pos/cv001_18431.txt
pos/cv002_15918.txt
pos/cv003_11664.txt
pos/cv004_11636.txt
pos/cv005_29443.txt
pos/cv006_15448.txt
pos/cv007_4968.txt
pos/cv008_29435.txt
pos/cv009_29592.txt
pos/cv010_29198.txt
pos/cv011_12166.txt
pos/cv012_29576.txt
pos/cv013_10159.txt
pos/cv014_13924.txt
pos/cv015_29439.txt
pos/cv016_4659.txt
pos/cv017_22464.txt
pos/cv018_20137.txt
pos/cv019_14482.txt
pos/cv020_8825.txt
pos/cv021_15838.txt
pos/cv022_12864.txt
pos/cv023_12672.txt
pos/cv024_6778.txt
pos/cv025_3108.txt
pos/cv026_29325.txt
pos/cv027_25219.txt
pos/cv028_26746.txt
pos/cv029_18643.txt
pos/cv030_21593.txt
pos/cv031_18452.txt
pos/cv032_22550.txt
pos/cv033_24444.txt
pos/cv034_29647.txt
pos/cv035_3954.txt
pos/cv036_16831.txt
pos/cv037_18510.txt
pos/cv038_9749.txt
pos/cv039_6170.txt
pos/cv040_8276.txt
pos/cv041_21113.txt
pos/cv042_10982.txt
pos/cv043_15013.txt
pos/cv044_16969.txt
pos/cv045_23923.txt
pos/cv046_10188.txt
pos/cv047_1754.txt
pos/cv048_16828.txt
pos/cv049_20471.txt
pos/cv050_

In [31]:
pos_words = []
for x in nltk.corpus.movie_reviews.fileids():
    if 'pos' in x:
        pos_words += list(nltk.corpus.movie_reviews.words(x))

In [33]:
pos_list = ['pos' for x in range(0,832564)]
len(pos_list)

832564

In [34]:
data = neg_words + pos_words
target = neg_list + pos_list

In [19]:
from sklearn.svm import SVC

In [36]:
clf = SVC(gamma=0.001, C=100.)
clf = clf.fit(data, target)

ValueError: could not convert string to float: 'plot'

In [37]:
from sklearn.naive_bayes import MultinomialNB

In [38]:
help(MultinomialNB)

Help on class MultinomialNB in module sklearn.naive_bayes:

class MultinomialNB(BaseDiscreteNB)
 |  Naive Bayes classifier for multinomial models
 |  
 |  The multinomial Naive Bayes classifier is suitable for classification with
 |  discrete features (e.g., word counts for text classification). The
 |  multinomial distribution normally requires integer feature counts. However,
 |  in practice, fractional counts such as tf-idf may also work.
 |  
 |  Parameters
 |  ----------
 |  alpha : float, optional (default=1.0)
 |      Additive (Laplace/Lidstone) smoothing parameter
 |      (0 for no smoothing).
 |  
 |  fit_prior : boolean
 |      Whether to learn class prior probabilities or not.
 |      If false, a uniform prior will be used.
 |  
 |  class_prior : array-like, size (n_classes,)
 |      Prior probabilities of the classes. If specified the priors are not
 |      adjusted according to the data.
 |  
 |  Attributes
 |  ----------
 |  class_log_prior_ : array, shape (n_classes, )
 

In [39]:
nb = 

In [110]:
nb = MultinomialNB().fit(data, target)

TypeError: unorderable types: numpy.ndarray() < int()

In [46]:
target = np.array(nltk.corpus.movie_reviews.categories())

In [47]:
target

array(['neg', 'pos'], 
      dtype='<U3')

In [139]:
data = []
for x in nltk.corpus.movie_reviews.fileids():
    if 'neg' in x:
        data.append((nltk.corpus.movie_reviews.raw(x), 'neg'))
    elif 'pos' in x:
        data.append((nltk.corpus.movie_reviews.raw(x), 'pos'))

In [94]:
data = np.array([clean_neg, clean_pos])

In [95]:
data.shape

(2, 628196)

In [64]:
len(data[0])

751256

In [66]:
t_pos = pos[:751256]

In [71]:
type(t_pos)

list

In [72]:
temp = np.array(t_pos)

In [97]:
sorted(np.unique(clean_neg))

['a',
 'aa',
 'aaa',
 'aaaaaaaaah',
 'aaaaaaaahhhh',
 'aaaaaah',
 'aaliyah',
 'aalyah',
 'aaron',
 'aatish',
 'ab',
 'aback',
 'abandon',
 'abandoned',
 'abandoning',
 'abandonment',
 'abandons',
 'abating',
 'abberation',
 'abbott',
 'abbreviated',
 'abby',
 'abc',
 'abdomen',
 'abducted',
 'abduction',
 'abductions',
 'abe',
 'abel',
 'aberdeen',
 'aberration',
 'abetting',
 'abhorrent',
 'abiding',
 'abigail',
 'abilities',
 'ability',
 'abject',
 'ablaze',
 'able',
 'ably',
 'abnormally',
 'abo',
 'aboard',
 'abode',
 'abolish',
 'abominable',
 'abomination',
 'aborigine',
 'abort',
 'aborted',
 'abortion',
 'abortive',
 'aboslutely',
 'abound',
 'abounding',
 'abounds',
 'about',
 'abouts',
 'above',
 'abraded',
 'abraham',
 'abrahams',
 'abrams',
 'abrasive',
 'abreast',
 'abril',
 'abroad',
 'abrupt',
 'abruptly',
 'abs',
 'absconded',
 'absence',
 'absences',
 'absent',
 'absentee',
 'absinthe',
 'absoltuely',
 'absolut',
 'absolute',
 'absolutely',
 'absolution',
 'absorb',
 '

In [91]:
import re
pat = re.compile(r"^[A-Za-z]*$")
len((list(filter(lambda i: pat.search(i), temp))))

633212

In [92]:
print(len((list(filter(lambda i: pat.search(i), pos)))))
print(len((list(filter(lambda i: pat.search(i), neg)))))

701557
628196


In [93]:
clean_pos = list(filter(lambda i: pat.search(i), pos))[:628196]
clean_neg = list(filter(lambda i: pat.search(i), neg))

In [98]:
np.random.randint(5, size=(6, 100))

array([[2, 1, 4, 2, 2, 2, 2, 4, 3, 3, 0, 2, 3, 4, 3, 3, 4, 4, 3, 1, 1, 0,
        3, 1, 1, 0, 4, 4, 0, 3, 0, 4, 3, 3, 2, 4, 2, 2, 3, 3, 1, 0, 4, 2,
        2, 4, 1, 4, 3, 4, 3, 2, 3, 4, 0, 1, 4, 1, 4, 0, 1, 1, 0, 2, 3, 3,
        2, 0, 0, 2, 1, 2, 3, 2, 4, 3, 1, 3, 3, 1, 0, 4, 0, 3, 1, 1, 4, 1,
        2, 2, 1, 4, 0, 0, 1, 2, 4, 2, 1, 1],
       [4, 0, 4, 3, 2, 4, 1, 1, 2, 1, 2, 1, 1, 4, 1, 0, 1, 4, 3, 2, 1, 3,
        1, 1, 1, 3, 1, 2, 4, 0, 3, 0, 0, 1, 3, 2, 1, 2, 4, 3, 1, 0, 2, 4,
        4, 4, 2, 3, 2, 3, 1, 4, 0, 0, 1, 1, 1, 0, 4, 1, 3, 1, 2, 4, 0, 3,
        1, 0, 2, 0, 4, 0, 2, 0, 1, 1, 4, 2, 0, 0, 1, 0, 4, 2, 3, 1, 1, 3,
        4, 3, 2, 0, 0, 2, 0, 4, 0, 0, 3, 2],
       [2, 0, 4, 2, 0, 3, 3, 0, 2, 4, 1, 4, 1, 3, 1, 0, 0, 2, 4, 2, 4, 3,
        1, 4, 4, 0, 3, 1, 1, 3, 0, 2, 0, 3, 2, 2, 1, 1, 4, 4, 3, 2, 0, 4,
        0, 1, 0, 1, 4, 4, 0, 0, 1, 2, 1, 3, 2, 3, 0, 1, 3, 3, 3, 1, 2, 1,
        2, 0, 0, 0, 1, 3, 0, 1, 0, 3, 0, 3, 4, 2, 4, 4, 1, 4, 1, 0, 3, 1,
        2, 1, 4, 3, 3,

In [107]:
for x in data[1]:
    if type(x) != np.str_:
        print(x)

In [100]:
type(data[0][0])

numpy.str_

In [108]:
target

array(['neg', 'pos'], 
      dtype='<U3')

In [109]:
target = np.array([0,1])

In [111]:
import numpy as np
X = np.random.randint(5, size=(6, 100))
y = np.array([1, 2, 3, 4, 5, 6])
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB()
clf.fit(X, y)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [113]:
clf.predict(X[:2])

array([1, 2])

In [114]:
data

array([['plot', 'two', 'teen', ..., 'exactly', 'the', 'same'],
       ['films', 'adapted', 'from', ..., 'melodrama', 'by', 'having']], 
      dtype='<U25')

In [115]:
from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer()

In [116]:
clean_pos

['films',
 'adapted',
 'from',
 'comic',
 'books',
 'have',
 'had',
 'plenty',
 'of',
 'success',
 'whether',
 'they',
 're',
 'about',
 'superheroes',
 'batman',
 'superman',
 'spawn',
 'or',
 'geared',
 'toward',
 'kids',
 'casper',
 'or',
 'the',
 'arthouse',
 'crowd',
 'ghost',
 'world',
 'but',
 'there',
 's',
 'never',
 'really',
 'been',
 'a',
 'comic',
 'book',
 'like',
 'from',
 'hell',
 'before',
 'for',
 'starters',
 'it',
 'was',
 'created',
 'by',
 'alan',
 'moore',
 'and',
 'eddie',
 'campbell',
 'who',
 'brought',
 'the',
 'medium',
 'to',
 'a',
 'whole',
 'new',
 'level',
 'in',
 'the',
 'mid',
 'with',
 'a',
 'part',
 'series',
 'called',
 'the',
 'watchmen',
 'to',
 'say',
 'moore',
 'and',
 'campbell',
 'thoroughly',
 'researched',
 'the',
 'subject',
 'of',
 'jack',
 'the',
 'ripper',
 'would',
 'be',
 'like',
 'saying',
 'michael',
 'jackson',
 'is',
 'starting',
 'to',
 'look',
 'a',
 'little',
 'odd',
 'the',
 'book',
 'or',
 'graphic',
 'novel',
 'if',
 'you',
 

In [140]:
data = []
for x in nltk.corpus.movie_reviews.fileids():
    if 'neg' in x:
        data.append((nltk.corpus.movie_reviews.raw(x), 'neg'))
    elif 'pos' in x:
        data.append((nltk.corpus.movie_reviews.raw(x), 'pos'))

In [141]:
train_data, target = zip(*data)

In [142]:
len(train_data)

2000

In [128]:
len(target)

2000

In [143]:
from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer()

In [144]:
X_train_counts = count_vect.fit_transform(train_data)
X_train_counts.shape

(2000, 39659)

In [145]:
from sklearn.feature_extraction.text import TfidfTransformer
tf_transformer = TfidfTransformer(use_idf=False).fit(X_train_counts)
X_train_tf = tf_transformer.transform(X_train_counts)
X_train_tf.shape

(2000, 39659)

In [146]:
tfidf_transformer = TfidfTransformer()
X_train_tfidf = tfidf_transformer.fit_transform(X_train_counts)

In [147]:
X_train_tfidf.shape

(2000, 39659)

In [148]:
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB().fit(X_train_tfidf, target)

In [167]:
docs_new = ['best', 'The plot was bad']
X_new_counts = count_vect.transform(docs_new)

In [168]:
X_new_tfidf = tfidf_transformer.transform(X_new_counts)

In [169]:
predicted = clf.predict(X_new_tfidf)

In [170]:
predicted

array(['pos', 'neg'], 
      dtype='<U3')

In [157]:
dir(clf)

['__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_cache',
 '_abc_negative_cache',
 '_abc_negative_cache_version',
 '_abc_registry',
 '_count',
 '_get_coef',
 '_get_intercept',
 '_get_param_names',
 '_joint_log_likelihood',
 '_update_class_log_prior',
 '_update_feature_log_prob',
 'alpha',
 'class_count_',
 'class_log_prior_',
 'class_prior',
 'classes_',
 'coef_',
 'feature_count_',
 'feature_log_prob_',
 'fit',
 'fit_prior',
 'get_params',
 'intercept_',
 'partial_fit',
 'predict',
 'predict_log_proba',
 'predict_proba',
 'score',
 'set_params']

In [158]:
clf.feature_count_

array([[ 0.32635585,  1.83965949,  0.        , ...,  0.05839863,
         0.        ,  0.06247761],
       [ 0.10757552,  1.63553843,  0.05120711, ...,  0.05915141,
         0.13438475,  0.        ]])

In [171]:
dir(movie_reviews)

['_MAX_REPR_SIZE',
 '__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__mul__',
 '__ne__',
 '__new__',
 '__radd__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__unicode__',
 '__weakref__',
 '_offsets',
 '_open_piece',
 '_pieces',
 'close',
 'count',
 'index',
 'iterate_from',
 'unicode_repr']

In [176]:
nltk.corpus.movie_reviews.sents()[:3]

[['plot',
  ':',
  'two',
  'teen',
  'couples',
  'go',
  'to',
  'a',
  'church',
  'party',
  ',',
  'drink',
  'and',
  'then',
  'drive',
  '.'],
 ['they', 'get', 'into', 'an', 'accident', '.'],
 ['one',
  'of',
  'the',
  'guys',
  'dies',
  ',',
  'but',
  'his',
  'girlfriend',
  'continues',
  'to',
  'see',
  'him',
  'in',
  'her',
  'life',
  ',',
  'and',
  'has',
  'nightmares',
  '.']]

In [179]:
from nltk.corpus import wordnet as wn

In [180]:
dir(wn)

['_LazyCorpusLoader__args',
 '_LazyCorpusLoader__kwargs',
 '_LazyCorpusLoader__load',
 '_LazyCorpusLoader__name',
 '_LazyCorpusLoader__reader_cls',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__le__',
 '__lt__',
 '__module__',
 '__name__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__unicode__',
 '__weakref__',
 '_unload',
 'unicode_repr']

In [184]:
dir(wn.synsets('cat')[0])

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__slots__',
 '__str__',
 '__subclasshook__',
 '__unicode__',
 '__weakref__',
 '_all_hypernyms',
 '_definition',
 '_examples',
 '_frame_ids',
 '_hypernyms',
 '_instance_hypernyms',
 '_iter_hypernym_lists',
 '_lemma_names',
 '_lemma_pointers',
 '_lemmas',
 '_lexname',
 '_max_depth',
 '_min_depth',
 '_name',
 '_needs_root',
 '_offset',
 '_pointers',
 '_pos',
 '_related',
 '_shortest_hypernym_paths',
 '_wordnet_corpus_reader',
 'also_sees',
 'attributes',
 'causes',
 'closure',
 'common_hypernyms',
 'definition',
 'entailments',
 'examples',
 'frame_ids',
 'hypernym_distances',
 'hypernym_paths',
 'hypernyms',
 'hyponyms',
 'instance_hypernyms',
 'instance_hyponyms',
 'jcn_similarity',
 'lch_si

In [191]:
wn.synsets('run')

[Synset('run.n.01'),
 Synset('test.n.05'),
 Synset('footrace.n.01'),
 Synset('streak.n.01'),
 Synset('run.n.05'),
 Synset('run.n.06'),
 Synset('run.n.07'),
 Synset('run.n.08'),
 Synset('run.n.09'),
 Synset('run.n.10'),
 Synset('rivulet.n.01'),
 Synset('political_campaign.n.01'),
 Synset('run.n.13'),
 Synset('discharge.n.06'),
 Synset('run.n.15'),
 Synset('run.n.16'),
 Synset('run.v.01'),
 Synset('scat.v.01'),
 Synset('run.v.03'),
 Synset('operate.v.01'),
 Synset('run.v.05'),
 Synset('run.v.06'),
 Synset('function.v.01'),
 Synset('range.v.01'),
 Synset('campaign.v.01'),
 Synset('play.v.18'),
 Synset('run.v.11'),
 Synset('tend.v.01'),
 Synset('run.v.13'),
 Synset('run.v.14'),
 Synset('run.v.15'),
 Synset('run.v.16'),
 Synset('prevail.v.03'),
 Synset('run.v.18'),
 Synset('run.v.19'),
 Synset('carry.v.15'),
 Synset('run.v.21'),
 Synset('guide.v.05'),
 Synset('run.v.23'),
 Synset('run.v.24'),
 Synset('run.v.25'),
 Synset('run.v.26'),
 Synset('run.v.27'),
 Synset('run.v.28'),
 Synset('run.v.

In [192]:
help(wn)

Help on WordNetCorpusReader in module nltk.corpus.reader.wordnet object:

class WordNetCorpusReader(nltk.corpus.reader.api.CorpusReader)
 |  A corpus reader used to access wordnet or its variants.
 |  
 |  Method resolution order:
 |      WordNetCorpusReader
 |      nltk.corpus.reader.api.CorpusReader
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __init__(self, root, omw_reader)
 |      Construct a new wordnet corpus reader, with the given root
 |      directory.
 |  
 |  all_lemma_names(self, pos=None, lang='en')
 |      Return all lemma names for all synsets for the given
 |      part of speech tag and langauge or languages. If pos is not specified, all synsets
 |      for all parts of speech will be used.
 |  
 |  all_synsets(self, pos=None)
 |      Iterate over all synsets with a given part of speech tag.
 |      If no pos is specified, all synsets for all parts of speech
 |      will be loaded.
 |  
 |  get_version(self)
 |  
 |  ic(self, corpus, weight_senses_eq

In [203]:
verbs = []
for s in wn.all_synsets(pos=wn.VERB):
    for l in s.lemma_names():
        verbs.append(l)

In [204]:
len(verbs)

25047

In [205]:
len(set(verbs))

11531

In [206]:
verbs=set(list(verbs))

In [207]:
len(verbs)

11531

In [210]:
nltk.corpus.movie_reviews.fileids()

['neg/cv000_29416.txt',
 'neg/cv001_19502.txt',
 'neg/cv002_17424.txt',
 'neg/cv003_12683.txt',
 'neg/cv004_12641.txt',
 'neg/cv005_29357.txt',
 'neg/cv006_17022.txt',
 'neg/cv007_4992.txt',
 'neg/cv008_29326.txt',
 'neg/cv009_29417.txt',
 'neg/cv010_29063.txt',
 'neg/cv011_13044.txt',
 'neg/cv012_29411.txt',
 'neg/cv013_10494.txt',
 'neg/cv014_15600.txt',
 'neg/cv015_29356.txt',
 'neg/cv016_4348.txt',
 'neg/cv017_23487.txt',
 'neg/cv018_21672.txt',
 'neg/cv019_16117.txt',
 'neg/cv020_9234.txt',
 'neg/cv021_17313.txt',
 'neg/cv022_14227.txt',
 'neg/cv023_13847.txt',
 'neg/cv024_7033.txt',
 'neg/cv025_29825.txt',
 'neg/cv026_29229.txt',
 'neg/cv027_26270.txt',
 'neg/cv028_26964.txt',
 'neg/cv029_19943.txt',
 'neg/cv030_22893.txt',
 'neg/cv031_19540.txt',
 'neg/cv032_23718.txt',
 'neg/cv033_25680.txt',
 'neg/cv034_29446.txt',
 'neg/cv035_3343.txt',
 'neg/cv036_18385.txt',
 'neg/cv037_19798.txt',
 'neg/cv038_9781.txt',
 'neg/cv039_5963.txt',
 'neg/cv040_8829.txt',
 'neg/cv041_22364.txt',


In [209]:
'I LIKED THE MOVIE BUT THE TRAILERS WERE BAD'

'I LIKED THE MOVIE BUT THE TRAILERS WERE BAD'

In [245]:
import os
politics_dir = '/Users/benkaufman/Downloads/SomasundaranWiebe-politicalDebates/'
politics_file_ids = []
for x in os.listdir(politics_dir):
    if os.path.isdir(politics_dir+x):
        for y in os.listdir(politics_dir+x):
            try:
                f = open(politics_dir+x+'/'+y, 'r')
                lines = f.readlines()
                f.close()
                f = open(politics_dir+x+'/'+y, 'w')
                f.writelines(lines[3:])
                f.close()
                politics_file_ids.append(x+'/'+y)
                print(x+'/'+y)
            except:
                pass
                #print(x+'/'+y)

abortion/post_0
abortion/post_1
abortion/post_10
abortion/post_1000
abortion/post_1001
abortion/post_1002
abortion/post_1003
abortion/post_1004
abortion/post_1005
abortion/post_1006
abortion/post_1007
abortion/post_1008
abortion/post_1009
abortion/post_101
abortion/post_1010
abortion/post_1011
abortion/post_1012
abortion/post_1013
abortion/post_1014
abortion/post_1015
abortion/post_1016
abortion/post_1017
abortion/post_1018
abortion/post_1019
abortion/post_1020
abortion/post_1021
abortion/post_1022
abortion/post_1023
abortion/post_1025
abortion/post_1026
abortion/post_1027
abortion/post_1028
abortion/post_1029
abortion/post_1030
abortion/post_1031
abortion/post_1032
abortion/post_1036
abortion/post_1037
abortion/post_1039
abortion/post_104
abortion/post_1040
abortion/post_1041
abortion/post_1043
abortion/post_1046
abortion/post_1048
abortion/post_1049
abortion/post_105
abortion/post_1050
abortion/post_1051
abortion/post_1052
abortion/post_1053
abortion/post_1054
abortion/post_1056
abor

In [240]:
politics_file_ids

['abortion/post_0',
 'abortion/post_1',
 'abortion/post_10',
 'abortion/post_1000',
 'abortion/post_1001',
 'abortion/post_1002',
 'abortion/post_1003',
 'abortion/post_1004',
 'abortion/post_1005',
 'abortion/post_1006',
 'abortion/post_1007',
 'abortion/post_1008',
 'abortion/post_1009',
 'abortion/post_101',
 'abortion/post_1010',
 'abortion/post_1011',
 'abortion/post_1012',
 'abortion/post_1013',
 'abortion/post_1014',
 'abortion/post_1015',
 'abortion/post_1016',
 'abortion/post_1017',
 'abortion/post_1018',
 'abortion/post_1019',
 'abortion/post_1020',
 'abortion/post_1021',
 'abortion/post_1022',
 'abortion/post_1023',
 'abortion/post_1025',
 'abortion/post_1026',
 'abortion/post_1027',
 'abortion/post_1028',
 'abortion/post_1029',
 'abortion/post_1030',
 'abortion/post_1031',
 'abortion/post_1032',
 'abortion/post_1036',
 'abortion/post_1037',
 'abortion/post_1039',
 'abortion/post_104',
 'abortion/post_1040',
 'abortion/post_1041',
 'abortion/post_1043',
 'abortion/post_1046'

In [246]:
from nltk.corpus import PlaintextCorpusReader
politics = PlaintextCorpusReader(politics_dir, politics_file_ids)

In [254]:
dir(politics)

['CorpusView',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__unicode__',
 '__weakref__',
 '_encoding',
 '_fileids',
 '_get_root',
 '_para_block_reader',
 '_read_para_block',
 '_read_sent_block',
 '_read_word_block',
 '_root',
 '_sent_tokenizer',
 '_tagset',
 '_word_tokenizer',
 'abspath',
 'abspaths',
 'encoding',
 'ensure_loaded',
 'fileids',
 'open',
 'paras',
 'raw',
 'readme',
 'root',
 'sents',
 'unicode_repr',
 'words']

[4, 5, 6]

In [225]:
os.listdir(politics_dir+'abortion')

['post_0',
 'post_1',
 'post_10',
 'post_100',
 'post_1000',
 'post_1001',
 'post_1002',
 'post_1003',
 'post_1004',
 'post_1005',
 'post_1006',
 'post_1007',
 'post_1008',
 'post_1009',
 'post_101',
 'post_1010',
 'post_1011',
 'post_1012',
 'post_1013',
 'post_1014',
 'post_1015',
 'post_1016',
 'post_1017',
 'post_1018',
 'post_1019',
 'post_102',
 'post_1020',
 'post_1021',
 'post_1022',
 'post_1023',
 'post_1024',
 'post_1025',
 'post_1026',
 'post_1027',
 'post_1028',
 'post_1029',
 'post_103',
 'post_1030',
 'post_1031',
 'post_1032',
 'post_1033',
 'post_1034',
 'post_1035',
 'post_1036',
 'post_1037',
 'post_1038',
 'post_1039',
 'post_104',
 'post_1040',
 'post_1041',
 'post_1042',
 'post_1043',
 'post_1044',
 'post_1045',
 'post_1046',
 'post_1047',
 'post_1048',
 'post_1049',
 'post_105',
 'post_1050',
 'post_1051',
 'post_1052',
 'post_1053',
 'post_1054',
 'post_1055',
 'post_1056',
 'post_1057',
 'post_1058',
 'post_1059',
 'post_106',
 'post_1060',
 'post_1061',
 'post_

In [255]:
politics_target = ['abortion', 'gayRights', 'creation', 'god', 'healthcare', 'guns']
politics_data = []
for x in politics.fileids():
    if 'abortion' in x:
        politics_data.append((politics.raw(x), 'abortion'))
    elif 'gayRights' in x:
        politics_data.append((politics.raw(x), 'gayRights'))
    elif 'creation' in x:
        politics_data.append((politics.raw(x), 'creation'))
    elif 'god' in x:
        politics_data.append((politics.raw(x), 'god'))
    elif 'healthcare' in x:
        politics_data.append((politics.raw(x), 'healthcare'))
    elif 'guns' in x:
        politics_data.append((politics.raw(x), 'guns'))

In [313]:
from random import shuffle
shuffle(politics_data)
politics_train_data, politics_targets = zip(*politics_data[:4500])
politics_score_data, politics_score_targets = zip(*politics_data[4500:])
from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer()

X_politics_train_counts = count_vect.fit_transform(politics_train_data)
print(X_politics_train_counts.shape)

from sklearn.feature_extraction.text import TfidfTransformer
tf_transformer = TfidfTransformer(use_idf=False).fit(X_politics_train_counts)
X_politics_train_tf = tf_transformer.transform(X_politics_train_counts)
print(X_politics_train_tf.shape)

tfidf_transformer = TfidfTransformer()
X_politics_train_tfidf = tfidf_transformer.fit_transform(X_politics_train_counts)

from sklearn.naive_bayes import MultinomialNB
politics_clf = MultinomialNB(alpha=0.01).fit(X_politics_train_tfidf, politics_targets)

(4500, 20844)
(4500, 20844)


In [314]:
politics_stuff = ['Senate Majority Leader Bill Frist said Friday that "it is impossible" to have all Americans covered by health insurance, but he predicted that Congress would take incremental steps to expand coverage this year. The Tennessee Republican said his state was "going bankrupt" as a result of trying to achieve universal insurance coverage. "It is impossible to get everybody covered," he said at a meeting with journalists. "Its impossible to get to 100 percent."', 'on the third day god created the rainforest']
X_politics_new_counts = count_vect.transform(politics_stuff)

X_politics_new_tfidf = tfidf_transformer.transform(X_politics_new_counts)

politics_predicted = politics_clf.predict_log_proba(X_politics_new_tfidf)
print(politics_clf.predict(X_politics_new_tfidf))
print(politics_predicted)

['healthcare' 'creation']
[[-5.39551916 -8.52343243 -4.5526021  -9.49668937 -5.46746076 -0.01976648]
 [-1.85331147 -0.83339275 -1.86783329 -1.63120913 -3.15172847 -4.14892516]]


In [274]:
politics_clf.classes_

array(['abortion', 'creation', 'gayRights', 'god', 'guns', 'healthcare'], 
      dtype='<U10')

In [315]:
X_politics_score_counts = count_vect.transform(politics_score_data)
X_politics_score_tfidf = tfidf_transformer.transform(X_politics_score_counts)

politics_clf.score(X_politics_score_tfidf, politics_score_targets)

0.84657534246575339

In [282]:
X_politics_train_counts.shape

(6690, 24858)

In [294]:
from random import shuffle
[(1,2),(3,4),(5,6),(7,8),(9,10)][1:]


[(3, 4), (5, 6), (7, 8), (9, 10)]

In [293]:
len(politics_train_data)

6690

In [298]:
politics_score_targets

('gayRights',
 'god',
 'god',
 'gayRights',
 'guns',
 'gayRights',
 'gayRights',
 'creation',
 'abortion',
 'gayRights',
 'creation',
 'abortion',
 'healthcare',
 'guns',
 'creation',
 'guns',
 'creation',
 'creation',
 'gayRights',
 'creation',
 'creation',
 'guns',
 'gayRights',
 'guns',
 'gayRights',
 'gayRights',
 'guns',
 'gayRights',
 'gayRights',
 'gayRights',
 'healthcare',
 'guns',
 'god',
 'creation',
 'creation',
 'gayRights',
 'abortion',
 'god',
 'gayRights',
 'god',
 'creation',
 'healthcare',
 'god',
 'god',
 'healthcare',
 'creation',
 'gayRights',
 'healthcare',
 'guns',
 'gayRights',
 'gayRights',
 'gayRights',
 'gayRights',
 'guns',
 'gayRights',
 'creation',
 'gayRights',
 'gayRights',
 'gayRights',
 'gayRights',
 'god',
 'creation',
 'gayRights',
 'creation',
 'healthcare',
 'god',
 'gayRights',
 'guns',
 'guns',
 'creation',
 'creation',
 'creation',
 'abortion',
 'god',
 'god',
 'gayRights',
 'gayRights',
 'creation',
 'creation',
 'guns',
 'gayRights',
 'god',
 

In [303]:
politics_clf.alpha

1.0

In [304]:
np.logspace(-4, -1, 6)

array([ 0.0001    ,  0.00039811,  0.00158489,  0.00630957,  0.02511886,
        0.1       ])

In [306]:
from sklearn import svm
svc = svm.SVC(kernel='linear')
svc.fit(X_politics_train_tfidf,politics_targets)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0, degree=3, gamma=0.0,
  kernel='linear', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [312]:
temp = count_vect.transform()
temp2 = tfidf_transformer.transform(temp)
svc.predict(temp2)

TypeError: transform() missing 1 required positional argument: 'raw_documents'