In [132]:
import numpy as np
import scipy as sp
from scipy import linalg as LA

In [39]:
# Ideally I'd use something like this, a generalized iteration function
# for Euler/Runge-Kutta methods but I found that I got more floating point
# arithmetic error

"""
def general_iteration(xr,yr,hr,func,itfunc,end):
    if xr >= end:
        return yr
    else:
        print(xr,yr)
        return eulers_method(xr+hr,
                    itfunc(xr,yr,hr,func),
                    hr,
                    func,
                    end)
"""


In [45]:
# Euler's Method

def my_func(x,y):
    """ User-defined ODE.
    
    This is a first order ODE of the form
                y' = f(x,y)
    the function returned by my_func should reflect f(x,y)
    
    Args:
        x: A single x-value
        y: A single y-value
        
    Returns:
        The output of the function.
    """
    return x-y


def tangent_approximation(x,y,h,f):
    """ Tangent line approximation.
    
    This is the linear approximation of the line tangent to
    f(x,y) at the point x, y, using a step size of h.
    
    Args:
        x: A single x-value
        y: A single y-value
        h: The step size
        f: The first derivative of the function y(x)
    
    Returns:
        An approximation of the value of y at that point.
    """
    return y + h*f(x,y)

def eulers_method(x,y,h,func,end):
    """ Euler's method for solving ODEs.
    
    This is Euler's method which approximates the solution to 
    an ODE (func) at a point whose "x" value is (end) given some 
    initial conditions (x,y)
    
    Args:
        x: The x-value of the initial condition
        y: The y-value of the initial condition
        h: The step size
        f: The first derivative of the function y(x)
        end: The x-value of the point at which you would like
             to approximate the value of y.
    
    Returns:
        An approximation of the value of y(end) given the 
        initial condition and step size.
    """
    if x >= end:
        return y
    else:
        print(x,y)
        return eulers_method(x+h,
                    tangent_approximation(x,y,h,func),
                    h,
                    func,
                    end)

eulers_method(0,1,0.1,my_func,0.5)

0 1
0.1 0.9
0.2 0.8200000000000001
0.30000000000000004 0.758
0.4 0.7122


0.68098

In [44]:
# Generalized Runge-Kutta Methods

def my_ode(x,y):
    return x-y

def rk4_approximation(x,y,h,f):
    k1 = f(x,y)
    k2 = f(x+(h/2),y+(k1*(h/2)))
    k3 = f(x+(h/2),y+(k2*(h/2)))
    k4 = f(x,y+(k3*h))
    return y + (sum([k1,2*k2,2*k3,k4])*(h/6))


def rk4(x,y,h,func,end):
    if x >= end:
        return y
    else:
        print(x,y)
        return rk4(x+h,
                    rk4_approximation(x,y,h,func),
                    h,
                    func,
                    end)

rk4(0,1,0.05,my_ode,0.5)

0 1
0.05 0.9520421875
0.1 0.9088618336372885
0.15000000000000002 0.870225939017039
0.2 0.8359128677584005
0.25 0.8057117932894095
0.3 0.7794221711708034
0.35 0.7568532376305177
0.39999999999999997 0.7378235325549433
0.44999999999999996 0.7221604457441732
0.49999999999999994 0.7096997852966411


0.7002853670438887

3.125000000000001e-07

In [225]:
# Computation of Eigenvalues
# Power Methods
n = 2
A = np.mat([[2,-1],[-1,2]])
#A = np.mat([[3,1,0],[1,4,0.5],[0,0.5,5]])

def power_it(A,n):
    u = np.mat(np.append(np.array(1),np.zeros(A.shape[0]-1))).T # initial guess
    w = np.mat(np.append(np.array(1),np.zeros(A.shape[0]-1))).T
    alpha = 0
    for _ in range(0,n):
        u = np.dot(A,w)
        alpha = u.item((0,0))
        w = u / alpha
    return alpha, w

power_it_res = power_it(A,100)
print("Largest Eigenvalue:", power_it_res[0])
print("Largest Eigenvector:", power_it_res[1])

inv_power_it_res = power_it(LA.inv(A),100)
print("Smallest Eigenvalue:", inv_power_it_res[0])
print("Smallest Eigenvector:", inv_power_it_res[1])

Largest Eigenvalue: 3.0
Largest Eigenvector: [[ 1.]
 [-1.]]
Smallest Eigenvalue: 1.0
Smallest Eigenvector: [[ 1.]
 [ 1.]]


In [222]:
np.append(np.array(1),np.zeros(A.shape[0]-1))

array([ 1.,  0.])

In [209]:
# Power Method - compute largest eigenvalue
n = 2
A = np.mat([[2,-1],[-1,2]])
#A = np.mat([[3,1,0],[1,4,0.5],[0,0.5,5]])





(0, matrix([[1],
         [0]]))

In [ ]:
# Iterative Methods for Solving Ax=b

In [106]:
# Jacobi Iteration
A = np.mat([[2,-1],[-1,2]])
#A = np.mat([[2,1],[5,7]])
b = np.mat([11, 13]).T
x0 = np.mat([1,1]).T

S_jacobi = np.diag(np.diag(A))
T_jacobi = S_jacobi - A

S_gausdel = np.tril(A)
T_gausdel = -np.triu(A,k=1)

In [129]:
def ax_b_iteration(A,S,T,x,n):
    curr_x = x
    #S = S/w
    #T = T/w
    S_inv = LA.inv(S) # only compute "constants" once
    S_inv_b = np.dot(S_inv,b)
    S_inv_T = np.matmul(S_inv,T)/w
    for _ in range(0,n):
        # x_(n+1) = (S^(-1)T)x_n + S^(-1)b
        curr_x = np.dot(S_inv_T,curr_x) + S_inv_b
    return curr_x

In [123]:
ax_b_iteration(A,S_jacobi,T_jacobi,x0,2)

matrix([[ 9. ],
        [ 9.5]])

In [124]:
ax_b_iteration(A,S_gausdel,T_gausdel,x0,1)

matrix([[ 6. ],
        [ 9.5]])

In [125]:
ax_b_iteration(A,S_jacobi,T_jacobi,x0,100)

matrix([[ 11.66666667],
        [ 12.33333333]])

In [126]:
ax_b_iteration(A,S_gausdel,T_gausdel,x0,100)

matrix([[ 11.66666667],
        [ 12.33333333]])

In [131]:
# TODO: SOR - No current general formula to find optimal w for nxn matrix

matrix([[ 11.1402439 ],
        [ 12.07012195]])

In [11]:
np.matmul(LA.inv(S_gausdel),T_gausdel)

array([[ 0.        ,  0.1875    ],
       [ 0.        ,  0.11931818]])

In [119]:
LA.solve(A,b)

array([[ 11.66666667],
       [ 12.33333333]])

In [170]:
n = 2
phi = np.array([1,1])
w=0.9
A = np.array([[2,1],[1,2]])
#A = np.mat([[2,1],[5,7]])
b = np.array([11, 13])

for _ in range(0,1000):
    for i in range(0,n):
        sigma = [0,0]
        for j in range(0,n):
            if j != i:
                sigma += A[i][j]*phi[j]
        phi = (1-w)*phi + (w/A[i][i])*(b-sigma)


In [162]:
phi

array([ 11.35483871,  12.35483871])

In [172]:
LA.solve(A,b)

array([ 3.,  5.])

In [174]:
LA.eigvals(A)

array([ 3.+0.j,  1.+0.j])

[[2 1 0 4 1]
 [1 4 5 9 3]
 [0 7 5 3 1]
 [9 6 7 7 2]
 [6 2 4 5 5]]


In [257]:
A[i:m,i]

matrix([[1],
        [4],
        [7],
        [6],
        [2]])

In [287]:
A = np.array([[2,1,0,4,1],[1,4,5,9,3],[0,7,5,3,1],[9,6,7,7,2],[6,2,4,5,5]])
Q = np.eye(m)
m, n = A.shape
print(A)

for i in range(0,n):
    z = A[i:m,i]
    v = np.append(z[0]*LA.norm(z) - z[0],-z[1:])
    v = v / np.dot(v.conj().T,v)
    for j in range(0,n):
        A[i:m,j] = A[i:m,j] - 2*np.dot(v,np.dot(v.conj().T,A[i:m,j]))
    for j in range(0,n):
        Q[i:m,j] = Q[i:m,j] - 2*np.dot(v,np.dot(v.conj().T,Q[i:m,j]))    

[[2 1 0 4 1]
 [1 4 5 9 3]
 [0 7 5 3 1]
 [9 6 7 7 2]
 [6 2 4 5 5]]


In [334]:
#A = np.array([[2,1,0,4,1],[1,4,5,9,3],[0,7,5,3,1],[9,6,7,7,2],[6,2,4,5,5]])
A = np.random.rand(6,3)
Q = np.eye(m)
m, n = A.shape
print(A)
z = A[:,0]
print(z)
v = np.append(z[0] + np.sign(z[0])*LA.norm(z) ,z[1:])
print(v)
v = v / LA.norm(v)
print(v)
F = np.eye(m)- 2*(v*v)
#F = np.around(F,decimals=3)
print(F*A)

[[ 0.10930099  0.75204454  0.12097898]
 [ 0.86412674  0.67717628  0.23118457]
 [ 0.7676944   0.71507733  0.03560403]
 [ 0.5987274   0.63639141  0.61686414]
 [ 0.28493224  0.33931095  0.66082967]
 [ 0.60229764  0.5104853   0.43293042]]
[ 0.10930099  0.86412674  0.7676944   0.5987274   0.28493224  0.60229764]
[ 1.57573876  0.86412674  0.7676944   0.5987274   0.28493224  0.60229764]
[ 0.73298534  0.40196526  0.35710789  0.27850962  0.13254174  0.28017039]


ValueError: operands could not be broadcast together with shapes (6,6) (6,3) 

In [288]:
A

array([[2, 1, 0, 4, 1],
       [0, 3, 3, 7, 1],
       [0, 5, 4, 2, 0],
       [5, 3, 5, 5, 0],
       [2, 0, 2, 3, 3]])

In [291]:
np.allclose(Q,Qn)

False

In [290]:
Qn,R = LA.qr(A)

In [285]:
Q

array([[-0.34815531,  0.0051045 , -0.81206955,  0.3696388 ,  0.28752744],
       [-0.        , -0.50534546,  0.24664346,  0.7744041 , -0.28998494],
       [-0.        , -0.84224243, -0.05763074, -0.39598367,  0.36125243],
       [-0.87038828, -0.07146299,  0.12009763, -0.23764424, -0.40794492],
       [-0.34815531,  0.17355299,  0.51182547,  0.22447181,  0.73233485]])

In [286]:
R

array([[-5.74456265, -2.95932015, -5.04825202, -6.78902858, -1.39262125],
       [ 0.        , -5.93653302, -4.8952151 , -5.03814109,  0.020418  ],
       [ 0.        ,  0.        ,  2.13354649,  0.49892908,  0.97005032],
       [ 0.        ,  0.        ,  0.        ,  5.59261075,  1.81745833],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  2.19454705]])